<?php

namespace AppBundle\Repository;

/**
 * PartieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartieRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllPartieFromJoueur($user)
    {
        return $this->createQueryBuilder('p')
            ->where('p.joueur1 = :user')
            ->orWhere('p.joueur2 = :user')
            ->setParameter('user', $user)
            ->getQuery()
            ->getResult();
    }
}
