<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Partie extends \AppBundle\Entity\Partie implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Partie' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Partie' . "\0" . 'encours', '' . "\0" . 'AppBundle\\Entity\\Partie' . "\0" . 'listeDesBornes', '' . "\0" . 'AppBundle\\Entity\\Partie' . "\0" . 'timer', '' . "\0" . 'AppBundle\\Entity\\Partie' . "\0" . 'debutPartie', '' . "\0" . 'AppBundle\\Entity\\Partie' . "\0" . 'pioche', '' . "\0" . 'AppBundle\\Entity\\Partie' . "\0" . 'mainj1', '' . "\0" . 'AppBundle\\Entity\\Partie' . "\0" . 'mainj2', '' . "\0" . 'AppBundle\\Entity\\Partie' . "\0" . 'terrainj1', '' . "\0" . 'AppBundle\\Entity\\Partie' . "\0" . 'terrainj2', '' . "\0" . 'AppBundle\\Entity\\Partie' . "\0" . 'joueur1', '' . "\0" . 'AppBundle\\Entity\\Partie' . "\0" . 'joueur2', '' . "\0" . 'AppBundle\\Entity\\Partie' . "\0" . 'tourJoueur', '' . "\0" . 'AppBundle\\Entity\\Partie' . "\0" . 'gagnant'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Partie' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Partie' . "\0" . 'encours', '' . "\0" . 'AppBundle\\Entity\\Partie' . "\0" . 'listeDesBornes', '' . "\0" . 'AppBundle\\Entity\\Partie' . "\0" . 'timer', '' . "\0" . 'AppBundle\\Entity\\Partie' . "\0" . 'debutPartie', '' . "\0" . 'AppBundle\\Entity\\Partie' . "\0" . 'pioche', '' . "\0" . 'AppBundle\\Entity\\Partie' . "\0" . 'mainj1', '' . "\0" . 'AppBundle\\Entity\\Partie' . "\0" . 'mainj2', '' . "\0" . 'AppBundle\\Entity\\Partie' . "\0" . 'terrainj1', '' . "\0" . 'AppBundle\\Entity\\Partie' . "\0" . 'terrainj2', '' . "\0" . 'AppBundle\\Entity\\Partie' . "\0" . 'joueur1', '' . "\0" . 'AppBundle\\Entity\\Partie' . "\0" . 'joueur2', '' . "\0" . 'AppBundle\\Entity\\Partie' . "\0" . 'tourJoueur', '' . "\0" . 'AppBundle\\Entity\\Partie' . "\0" . 'gagnant'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Partie $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setEncours($encours)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEncours', [$encours]);

        return parent::setEncours($encours);
    }

    /**
     * {@inheritDoc}
     */
    public function getEncours()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEncours', []);

        return parent::getEncours();
    }

    /**
     * {@inheritDoc}
     */
    public function setListeDesBornes($listeDesBornes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setListeDesBornes', [$listeDesBornes]);

        return parent::setListeDesBornes($listeDesBornes);
    }

    /**
     * {@inheritDoc}
     */
    public function getListeDesBornes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getListeDesBornes', []);

        return parent::getListeDesBornes();
    }

    /**
     * {@inheritDoc}
     */
    public function setTimer($timer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTimer', [$timer]);

        return parent::setTimer($timer);
    }

    /**
     * {@inheritDoc}
     */
    public function getTimer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTimer', []);

        return parent::getTimer();
    }

    /**
     * {@inheritDoc}
     */
    public function setDebutPartie($debutPartie)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDebutPartie', [$debutPartie]);

        return parent::setDebutPartie($debutPartie);
    }

    /**
     * {@inheritDoc}
     */
    public function getDebutPartie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDebutPartie', []);

        return parent::getDebutPartie();
    }

    /**
     * {@inheritDoc}
     */
    public function setPioche($pioche)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPioche', [$pioche]);

        return parent::setPioche($pioche);
    }

    /**
     * {@inheritDoc}
     */
    public function getPioche()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPioche', []);

        return parent::getPioche();
    }

    /**
     * {@inheritDoc}
     */
    public function setMainj1($mainj1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMainj1', [$mainj1]);

        return parent::setMainj1($mainj1);
    }

    /**
     * {@inheritDoc}
     */
    public function getMainj1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMainj1', []);

        return parent::getMainj1();
    }

    /**
     * {@inheritDoc}
     */
    public function setMainj2($mainj2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMainj2', [$mainj2]);

        return parent::setMainj2($mainj2);
    }

    /**
     * {@inheritDoc}
     */
    public function getMainj2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMainj2', []);

        return parent::getMainj2();
    }

    /**
     * {@inheritDoc}
     */
    public function setTerrainj1($terrainj1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTerrainj1', [$terrainj1]);

        return parent::setTerrainj1($terrainj1);
    }

    /**
     * {@inheritDoc}
     */
    public function getTerrainj1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTerrainj1', []);

        return parent::getTerrainj1();
    }

    /**
     * {@inheritDoc}
     */
    public function setTerrainj2($terrainj2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTerrainj2', [$terrainj2]);

        return parent::setTerrainj2($terrainj2);
    }

    /**
     * {@inheritDoc}
     */
    public function getTerrainj2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTerrainj2', []);

        return parent::getTerrainj2();
    }

    /**
     * {@inheritDoc}
     */
    public function setJoueur1(\AppBundle\Entity\Joueur $joueur1 = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJoueur1', [$joueur1]);

        return parent::setJoueur1($joueur1);
    }

    /**
     * {@inheritDoc}
     */
    public function getJoueur1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJoueur1', []);

        return parent::getJoueur1();
    }

    /**
     * {@inheritDoc}
     */
    public function setJoueur2(\AppBundle\Entity\Joueur $joueur2 = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJoueur2', [$joueur2]);

        return parent::setJoueur2($joueur2);
    }

    /**
     * {@inheritDoc}
     */
    public function getJoueur2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJoueur2', []);

        return parent::getJoueur2();
    }

    /**
     * {@inheritDoc}
     */
    public function setTourJoueur(\AppBundle\Entity\Joueur $tourJoueur = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTourJoueur', [$tourJoueur]);

        return parent::setTourJoueur($tourJoueur);
    }

    /**
     * {@inheritDoc}
     */
    public function getTourJoueur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTourJoueur', []);

        return parent::getTourJoueur();
    }

    /**
     * {@inheritDoc}
     */
    public function setGagnant(\AppBundle\Entity\Joueur $gagnant = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGagnant', [$gagnant]);

        return parent::setGagnant($gagnant);
    }

    /**
     * {@inheritDoc}
     */
    public function getGagnant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGagnant', []);

        return parent::getGagnant();
    }

}
